var modules =
[
    [ "Basic Data Types", "group__basic__data__types.html", "group__basic__data__types" ],
    [ "Conversion Macros", "group__conversion__macros.html", "group__conversion__macros" ],
    [ "Creating Configuration Structure", "group__config__struct__macros.html", "group__config__struct__macros" ],
    [ "Basic I/O Operations", "group__io__operations.html", "group__io__operations" ],
    [ "MKMxxZxxACxx5 Platform Interface", "group__kinetiskm__interface.html", "group__kinetiskm__interface" ],
    [ "ADC Driver", "group__adc__drv.html", "group__adc__drv" ],
    [ "AFE Driver", "group__afe__drv.html", "group__afe__drv" ],
    [ "AIPS Driver", "group__aips__drv.html", "group__aips__drv" ],
    [ "CMP Driver", "group__cmp__drv.html", "group__cmp__drv" ],
    [ "CRC Driver", "group__crc__drv.html", "group__crc__drv" ],
    [ "DMA Driver", "group__dma__drv.html", "group__dma__drv" ],
    [ "EWM Driver", "group__ewm__drv.html", "group__ewm__drv" ],
    [ "FLL Driver", "group__fll__drv.html", "group__fll__drv" ],
    [ "FTFA Driver", "group__ftfa__drv.html", "group__ftfa__drv" ],
    [ "GPIO Driver", "group__gpio__drv.html", "group__gpio__drv" ],
    [ "IRTC Driver", "group__irtc__drv.html", "group__irtc__drv" ],
    [ "I2C Driver", "group__i2c__drv.html", "group__i2c__drv" ],
    [ "LLWU Driver", "group__llwu__drv.html", "group__llwu__drv" ],
    [ "LPTMR Driver", "group__lptmr__drv.html", "group__lptmr__drv" ],
    [ "MCM Driver", "group__mcm__drv.html", "group__mcm__drv" ],
    [ "MPU Driver", "group__mpu__drv.html", "group__mpu__drv" ],
    [ "OSC Driver", "group__osc__drv.html", "group__osc__drv" ],
    [ "OSC32K Driver", "group__osc32k__drv.html", "group__osc32k__drv" ],
    [ "PIT Driver", "group__pit__drv.html", "group__pit__drv" ],
    [ "PLL Driver", "group__pll__drv.html", "group__pll__drv" ],
    [ "PMC Driver", "group__pmc__drv.html", "group__pmc__drv" ],
    [ "RCM Driver", "group__rcm__drv.html", "group__rcm__drv" ],
    [ "RNGA Driver", "group__rnga__drv.html", "group__rnga__drv" ],
    [ "SIM Driver", "group__sim__drv.html", "group__sim__drv" ],
    [ "SMC Driver", "group__smc__drv.html", "group__smc__drv" ],
    [ "SPI Driver", "group__spi__drv.html", "group__spi__drv" ],
    [ "SWISR Driver", "group__swisr__drv.html", "group__swisr__drv" ],
    [ "SYST Driver", "group__syst__drv.html", "group__syst__drv" ],
    [ "TMR Driver", "group__tmr__drv.html", "group__tmr__drv" ],
    [ "UART Driver", "group__uart__drv.html", "group__uart__drv" ],
    [ "VREF Driver", "group__vref__drv.html", "group__vref__drv" ],
    [ "WDOG Driver", "group__wdog__drv.html", "group__wdog__drv" ],
    [ "XBAR Driver", "group__xbar__drv.html", "group__xbar__drv" ]
];