var searchData=
[
  ['adc_20hardware_20averaging_20options',['ADC Hardware Averaging Options',['../group__adc__avg__list.html',1,'']]],
  ['adc_20callback_20function',['ADC Callback Function',['../group__adc__callback.html',1,'']]],
  ['adc_20channel_20configuration_20structures',['ADC Channel Configuration Structures',['../group__adc__chan__config.html',1,'']]],
  ['adc_20input_20channels_20_28muxa_29',['ADC Input Channels (MUXA)',['../group__adc__chan__muxa.html',1,'']]],
  ['adc_20input_20channels_20_28muxb_29',['ADC Input Channels (MUXB)',['../group__adc__chan__muxb.html',1,'']]],
  ['adc_20driver',['ADC Driver',['../group__adc__drv.html',1,'']]],
  ['adc_20example',['ADC Example',['../group__adc__example.html',1,'']]],
  ['adc_20examples',['ADC Examples',['../group__adc__examples.html',1,'']]],
  ['adc_20api_20specification',['ADC API Specification',['../group__adc__macro.html',1,'']]],
  ['adc_20configuration_20structures',['ADC Configuration Structures',['../group__adc__module__config.html',1,'']]],
  ['adc_20operation_20from_20internal_201_2e0_20v_20pmc_20bandgap_20vref',['ADC Operation from Internal 1.0 V PMC Bandgap VREF',['../group__adcbandgap__example.html',1,'']]],
  ['afe_20callback_20function',['AFE Callback Function',['../group__afe__ch__callback.html',1,'']]],
  ['afe_20channel_20configuration_20structures',['AFE Channel Configuration Structures',['../group__afe__chan__config.html',1,'']]],
  ['afe_20clock_20dividers',['AFE Clock Dividers',['../group__afe__clkdiv.html',1,'']]],
  ['afe_20clock_20sources',['AFE Clock Sources',['../group__afe__clocks.html',1,'']]],
  ['afe_20driver',['AFE Driver',['../group__afe__drv.html',1,'']]],
  ['afe_20software_20trigger_20polling_20mode',['AFE Software Trigger Polling Mode',['../group__afe__example.html',1,'']]],
  ['afe_20examples',['AFE Examples',['../group__afe__examples.html',1,'']]],
  ['afe_20pga_20gain_20stages',['AFE PGA Gain Stages',['../group__afe__gain.html',1,'']]],
  ['afe_20api_20specification',['AFE API Specification',['../group__afe__macro.html',1,'']]],
  ['afe_20module_20configuration_20structures',['AFE Module Configuration Structures',['../group__afe__module__config.html',1,'']]],
  ['afe_20oversampling_20ratios',['AFE Oversampling Ratios',['../group__afe__osr.html',1,'']]],
  ['afe_20software_20trigger_20interrupt_20mode',['AFE Software Trigger Interrupt Mode',['../group__afeisr__example.html',1,'']]],
  ['afe_20low_20power_20operation',['AFE Low Power Operation',['../group__afelp__example.html',1,'']]],
  ['afe_20clocked_20by_208_2e0_20mhz_20osc_2c_20fei_20mode',['AFE Clocked by 8.0 MHz OSC, FEI Mode',['../group__afequartz__example.html',1,'']]],
  ['afe_20clocked_20by_20pll_20engaged_2032_2e768_20khz_20rtcosc_2c_20blpi_20mode',['AFE Clocked by PLL Engaged 32.768 KHz RTCOSC, BLPI Mode',['../group__afevlprpll__example.html',1,'']]],
  ['aips_20driver',['AIPS Driver',['../group__aips__drv.html',1,'']]],
  ['aips_20example',['AIPS Example',['../group__aips__example.html',1,'']]],
  ['aips_20api_20specification',['AIPS API Specification',['../group__aips__macro.html',1,'']]],
  ['aips_20peripheral_20slots',['AIPS Peripheral Slots',['../group__aips__slot.html',1,'']]],
  ['aips_20peripheral_20access_20attributes',['AIPS Peripheral Access Attributes',['../group__aips__slot__attr.html',1,'']]],
  ['arm_20cortex_2dm0_2b_20macros',['ARM Cortex-M0+ Macros',['../group__cm0plus__macros.html',1,'']]],
  ['arm_20cortex_2dm0_2b_20interrupt_20priority_20levels',['ARM Cortex-M0+ Interrupt Priority Levels',['../group__cm0plus__prilvl.html',1,'']]],
  ['afe_20clocked_20by_208_2e0_20mhz_20osc_2c_20fee_20mode',['AFE Clocked by 8.0 MHz OSC, FEE Mode',['../group__oscafe__example.html',1,'']]]
];
